class Manufacture < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: 'バタフライ' },
    { id: 3, name: 'Nittaku' },
    { id: 4, name: 'TSP' },
    { id: 5, name: 'Yasaka' },
    { id: 6, name: 'VICTAS' },
    { id: 7, name: 'ミズノ' },
    { id: 8, name: '紅双喜' },
    { id: 9, name: 'XIOM' },
    { id: 10, name: 'STIGA' },
    { id: 11, name: 'TIBHAR' },
    { id: 12, name: 'DONIC' },
    { id: 13, name: 'Joola' },
    { id: 14, name: 'Andro' },
    { id: 15, name: 'JUIC' },
    { id: 16, name: 'アームストロング' },
    { id: 17, name: '銀河' },
    { id: 18, name: 'ダーカー' },
    { id: 19, name: 'Dr.ノイバウア' },
    { id: 20, name: 'アバロックス' },
    { id: 21, name: 'その他' },
  ]
end
